### ISSUE TITLE
pl-map-analysis-tools

### ISSUE THREAD

**Issue by amcar-dtu** [dtudk/Admin#2]
**PL Map Analysis Tools**

MATLAB-based set of functions for analyzing PL maps obtained with our optical setup in Lab 930.

**License**

Private project to be kept it internally.

**Maintainer User**

Maintainer: team [electro-nanofotonik-2dmat](https://github.com/orgs/dtudk/teams/electro-nanofotonik-2dmat).

**SNF**

**Associated Data**

@zerothi 

cc @mofis-dtu

**Comment by zerothi** [comment]
Sorry, it glimpsed my site, I'll do this tomorrow, would this be fine?

**Comment by zerothi** [comment]
Ok, I did it :)

I have created a new team (as previously). Currently only you will be in the team. Let me know if more should be in the team (remember, max 3)

**Comment by amcar-dtu** [comment]
ok @zerothi thanks a lot! can you please add also @mofis-dtu to the brand new team [pl-map-analysis-tools](https://github.com/orgs/dtudk/teams/pl-map-analysis-tools)?
Also, I would like to ask: for the future, do you prefer that I collect all the repos to create so that you can do all of them just once, or you prefer a creation in batches with one/max two repos at one time?

**Comment by zerothi** [comment]
> ok @zerothi thanks a lot! can you please add also @mofis-dtu to the brand new team [pl-map-analysis-tools](https://github.com/orgs/dtudk/teams/pl-map-analysis-tools)? Also, I would like to ask: for the future, do you prefer that I collect all the repos to create so that you can do all of them just once, or you prefer a creation in batches with one/max two repos at one time?

Done, I would probably like everything at once, then I'll do them in the batch-sizes that fits me :)

**Comment by amcar-dtu** [comment]
hi @zerothi we have another colleague that needs to be added to all our groups and repos. Her user is @PoojaSindhuraj, could you please add her?
Thanks a lot.

**Comment by zerothi** [comment]
Done.

**Comment by amcar-dtu** [comment]
hi @zerothi we have a new user to add to DTU organization and our repositoryteam [pl-map-analysis-tools](https://github.com/orgs/dtudk/teams/pl-map-analysis-tools). Here the username: @s183777-dtu .
Can you please add her?
Best.

**Comment by zerothi** [comment]
done
